import socket
server = socket.socket()
server.bind(('0.0.0.0',5000))
server.listen(1)
client,addr=server.accept()
data=client.recv(1024)
print(f'收到:{data}')
client.send('收到!'.encode('UTF-8'))
client.close()
server.close()
